---
- name: Install CatUpload API server
  hosts: all

  tasks:
    - name: Install git and firewalld
      ansible.builtin.dnf:
        name:
          - git
          - firewalld
        state: latest
      become: yes

    - name: Start and enable firewalld service
      ansible.builtin.service:
        name: firewalld
        state: started
        enabled: yes
      become: yes
    
    - name: Expose port 3000
      ansible.posix.firewalld:
        zone: public
        port: 3000/tcp
        permanent: true
        state: enabled
      notify: Reload firewalld
      become: yes
    
    - name: Install nvm
      ansible.builtin.shell: >
        curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
        creates=/home/{{ ansible_user_id }}/.nvm/nvm.sh

    - name: Install node and npm
      ansible.builtin.shell: >
        source /home/{{ ansible_user_id }}/.nvm/nvm.sh && nvm install 22
        creates=/home/{{ ansible_user_id }}/.nvm/alias
    
    - name: Install forever
      community.general.npm:
        name: forever
        global: yes
        state: latest
    
    - name: Git checkout
      ansible.builtin.git:
        repo: "https://github.com/SethFranklin/CatUpload.git"
        dest: /home/{{ ansible_user_id }}/CatUpload
    
    - name: Npm install
      community.general.npm:
        path: /home/{{ ansible_user_id }}/CatUpload/nodejs
    
    - name: Copy .env file
      ansible.builtin.copy:
        src: .env
        dest: /home/{{ ansible_user_id }}/CatUpload/nodejs/.env

    - name: Check list of forever applications running
      ansible.builtin.command: forever list
      register: forever_list
      changed_when: false

    - name: Npm start forever
      ansible.builtin.command: forever start src/index.js
      args:
        chdir: /home/{{ ansible_user_id }}/CatUpload/nodejs
      when: "forever_list.stdout.find('npm start') == -1"
  
  handlers:
    - name: Reload firewalld
      ansible.builtin.service:
        name: firewalld
        state: reloaded
      become: yes